# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# or pod ‘Firebase/AnalyticsWithoutAdIdSupport’
# for Analytics without IDFA collection capability

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'QuizApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizApp

  target 'QuizAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuizAppUITests' do
    # Pods for testing
  end

end
